### ISSUE TITLE
Actualités - décalage titre / problème intégration

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#12]
https://mids.ch/en/posts/2024-10-30-new-websites-launch/

<img width="1401" alt="Capture d’écran 2024-10-31 à 09 46 21" src="https://github.com/user-attachments/assets/1c700a1b-60ac-4f6a-8741-6ca8026d77a5">

**Comment by Olivia206** [comment]
J'ai laissé la liste avec filets en haut à côté du summary, c'est ok ? ou on garde le sticky ?

**Comment by iphnir** [comment]
Yes c'est ok
