### ISSUE TITLE
News - page d'erreur

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#17]
Quand je suis là : https://cids.ch/about/news/2024-10-31-mids-2025-2026-applications-open/

et que je clic sur News dans le fil d'ariane, j'arrive sur une erreur : https://cids.ch/about/news/

**Comment by Olivia206** [comment]
Hello, c'est parce que la page est en brouillon ici : https://cids.osuny.org/admin/en/communication/websites/1f9c62e8-5cd7-4a3c-b0d9-29c83c9526ef/pages/4ccf9da0-9909-4886-9b36-9fb2e22c8461
(elle a été créée puis désactivée donc ça reste dans le fil d'ariane)

**Comment by Olivia206** [comment]
@iphnir il faut republier la page "news", d'une part pour assurer le bon fonctionnement du fil d'ariane, d'autre part pour permettre aux gens d'accéder à l'index des actualités
