### ISSUE TITLE
[QUESTION] Désactiver la table of content?

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#23]
Est-ce qu'il est possible de rendre déactivable le bouton "table of contents" sur certaines pages dans le backend? Comme par ex. sur les parent pages comme "[academics](https://mids.ch/academics/)", "student experience", "about" etc. où il n'est pas vraiment nécessaire.

**Comment by Olivia206** [comment]
Ce qu'on peut faire c'est créer une class personnalisée qu'il faudra ajouter dans le backoffice, oui (comme la couleur foncée de certaines pages)

**Comment by iphnir** [comment]
OK ce serait l'idéal en effet

**Comment by Olivia206** [comment]
Coucou, on peut ajouter dans le back la class `no-toc`, et sur les pages avec un fond bleu foncé ça enlève automatiquement le toc également
