### ISSUE TITLE
Agrandissement photos

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#27]
Sur les photos, la plupart peuvent encore être agrandies quand on clique dessus, on en avait rapidement parlé une fois, perso ça ne me déplait pas comme les photos sont de moi et que ça permet de les admirer hehe, mais je pense que ce serait plus pro de ne pas les rendre agrandissables ?

-> pourquoi pas si c'est pas trop compliqué à désactiver, d'autant qu'aujourd'hui quand elles s'agrandissent on voit encore la topbar, la Table of contents... 
<img width="1437" alt="Capture d’écran 2024-12-11 à 14 39 01" src="https://github.com/user-attachments/assets/625c958b-d1cf-44f1-b13b-47b4832817fb" />

**Comment by Olivia206** [comment]
Ah oui ça je n'avais pas vu !
On a une config pour désactiver ça donc c'est tout simple
