### ISSUE TITLE
Traitement des blocs people quand resize

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#29]
Le traitement des blocs people est différent entre les pages, quand on resize : 

Ex : ici, on reste sur 2 colonnes
https://mids.ch/community/faculty/

et ici, on passe sur 1 seule colonne : 
https://mids.ch/community/team-governance/

-> faire en sorte de rester sur 2 colonnes
est-ce que c'est dû à l'usage d'un bloc différent ?

**Comment by Olivia206** [comment]
C'est dû au fait qu'une page soit en full width (faculty) et l'autre non, j'ai harmonisé !
