### ISSUE TITLE
[QUESTION] Réduire hauteur menu ?

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#30]
Enfin, mais cette question est peut-être un poil plus controversial, est-ce que vous pensez qu'il serait possible d'amincir un poil la topbar ? Par exemple en abaissant les boutons switch et search et en les alignant sur le haut du logo MIDS ? Ici je me demande si l'alignement serait agréable visuellement, mais aussi et surtout parce qu'en faisant des tests sur des écrans à petite résolution, je me suis rendu compte que la top bar prenait beaucoup de place.

-> c'est vrai qu'elle est un peu grosse cette nav, qu'est-ce que tu en penses Olivia ?

**Comment by Olivia206** [comment]
Ça ne me choquerait pas, mais je pense qu'on devrait demander l'avis de Takumi, qu'en penses-tu @iphnir ?

Ce que je peux faire sans déformer la maquette, en revanche, c'est diminuer la taille du logo sous une certaine taille d'écran

**Comment by iphnir** [comment]
Oui ok pour l'avis de Takumi. Je le ping sur slack.

**Comment by Olivia206** [comment]
![Capture d’écran 2024-12-12 à 17 17 01](https://github.com/user-attachments/assets/f3206541-56bd-42c6-8430-f7cec7673a0d)
