### ISSUE TITLE
Mobile - menu - taille de typo

### ISSUE THREAD

**Issue by iphnir** [osunyorg/cids-theme#9]
Les tailles de typo sont un peu déséquilibrés.
je pense qu'il faut réduire la taille du titre (admissions)  et espacer + la description et les items du menu. 

![IMG_5723](https://github.com/user-attachments/assets/974d69f2-0688-4111-be03-76216e642eed)

**Comment by Olivia206** [comment]
comme ça, ça irait @iphnir ?
ou on garde la rand pour tous le texte/titre ?

![Capture d’écran 2024-10-31 à 11 15 35](https://github.com/user-attachments/assets/3dc3c271-41d2-4e6a-8457-246dca609669)

**Comment by iphnir** [comment]
Je réduirai d'1 ou 2 pt la police de la description pour clarifier un peu la hiérarchie de l'info. Mais c'est bien sinon

**Comment by iphnir** [comment]
Je réduirai d'1 ou 2 pt la police de la description pour clarifier un peu
la hiérarchie de l'info. Mais c'est bien sinon


Le jeu. 31 oct. 2024 à 11:16, Olivia Simonet ***@***.***> a
écrit :
